baseURL = 'http://www.adamportier.com/'
languageCode = 'en-us'
title = 'Adam Portier'
theme = 'hugo-sustain'
enableRobotsTXT = true

[permalinks]
  post = "/:year/:month/:day/:slug"
  
[params]
  author = "Adam Portier"
  avatar = "img/me_dec_2013.jpg"
  description = "Systems Administrator Working in higher education with a focus on Linux systems"
  
[params.social]
  Github = "ajportier"
  
[[menu.main]]
  name = "blog"
  weight = 1
  identifier = "blog"
  url = "/blog/"

[[menu.main]]
  name = "publications"
  weight = 2
  identifier = "publications"
  url = "/publications/"

[[menu.main]]
  name = "about"
  weight = 3
  identifier = "about"
  url = "/about/"
